Repository PostHog/posthog-js, pull requests merged in 2021-06, with the labels that each got.

#226 Retry Queue
  src/__tests__/posthog-core.js
  src/__tests__/retry-queue.js
  src/base-request-queue.js
  src/posthog-core.js
  src/request-queue.js
  src/retry-queue.js
  src/send-request.js
Labels: bump minor

#239 fix: avoid directly accessing localStorage
  src/posthog-core.js
Labels: bump patch

#241 Fix overridden request retry data
  src/send-request.js
Labels: bump patch, release-1.26.0

#246 Capture viewport size
  src/utils.js
Labels: bump patch

#250 Fix invalid cookie
  src/posthog-persistence.js
Labels: bump patch
