Repository PostHog/posthog-js, pull requests merged in 2022-03, with the labels that each got.

#368 fix(web performance): calculate duration when it isn't present on navigation timing
  src/__tests__/apm.js
  src/apm.js
Labels: bump patch, application-performance-monitoring

#351 feat: send library version outside of compressed body as a debug signal
  cypress/integration/capture.spec.js
  src/__tests__/send-request.js
  src/posthog-core.js
  src/send-request.js
Labels: enhancement, bump minor

#375 revert: "feat: send library version outside of compressed body as a debug signal"
  cypress/integration/capture.spec.js
  src/__tests__/send-request.js
  src/posthog-core.js
  src/send-request.js
Labels: bump patch

#376 feat: send library version outside of compressed body as a debug signal
  cypress/integration/capture.spec.js
  src/__tests__/send-request.js
  src/posthog-core.js
  src/send-request.js
Labels: bump minor

#378 feat(tracking): add ahrefsbot to list of ignored bots
  src/utils.js
Labels: bump patch

#377 fix(web-performance): clear resource timings after reading
  src/__tests__/posthog-core.js
  src/apm.js
Labels: bug, bump patch, feature/apm
