Repository PostHog/posthog-js, pull requests merged in 2022-12, with the labels that each got.

#478 fix: support copying non-extensible objects
  src/__tests__/utils.js
  src/utils.ts
Labels: bump patch

#479 chore: update sentry types
  package.json
  yarn.lock
Labels: bump patch

#481 feat: event_allowlist and url_allowlist for autocapture
  cypress/e2e/capture.cy.js
  src/__tests__/autocapture.js
  src/__tests__/posthog-core.js
  src/autocapture-utils.ts
  src/autocapture.ts
  src/posthog-core.ts
  src/types.ts
Labels: bump minor

#487 feat: page view ids
  src/__tests__/page-view-id.js
  src/page-view-id.ts
  src/posthog-core.ts
Labels: bump minor, lisbon-web-performance

#493 fix(ua): Add additional user-agents to ignore list
  src/utils.ts
Labels: bump minor

#488 feat: Adds performance capture
  README.md
  cypress/e2e/capture.cy.js
  cypress/e2e/web-performance.cy.js
  playground/session-recordings/index.html
  src/__tests__/apm.js
  src/__tests__/posthog-core.js
  src/apm.ts
  src/decide.ts
  src/extensions/web-performance.ts
  src/posthog-core.ts
  src/types.ts
Labels: bump minor, lisbon-web-performance
