Repository PostHog/posthog-js, pull requests merged in 2022-01, with the labels that each got.

#354 Reduce the size of the APM performance data payload
  cypress/integration/capture.spec.js
  src/__tests__/apm.js
  src/__tests__/optimised-very-large-performance-data.json
  src/__tests__/posthog-core.js
  src/__tests__/very-large-performance-data.json
  src/apm.js
  src/posthog-core.js
Labels: bug, bump patch

#357 Remove debug line
  src/extensions/toolbar.js
Labels: bump patch

#355 Add an allow list to skip truncating strings when capturing events
  src/__tests__/utils.js
  src/utils.js
Labels: enhancement, bump patch

#359 Fix featureflags not working when /decide is down
  src/__tests__/decide.js
  src/decide.js
Labels: bump patch

#360 Only hit onFeatureFlags callback after decide
  src/__tests__/featureflags.js
  src/decide.js
  src/posthog-core.js
  src/posthog-featureflags.js
Labels: bump patch

#362 Remove capture failed request
  src/__tests__/capture-metrics.js
  src/__tests__/send-request.js
  src/capture-metrics.js
  src/posthog-core.js
  src/send-request.js
Labels: bump patch
