Repository PostHog/posthog-js, pull requests merged in 2023-10, with the labels that each got.

#810 fix(surveys): Handle filtering on undefined
  src/__tests__/surveys.js
  src/posthog-surveys.ts
Labels: bump patch

#820 fix(capture): Always update stored person props from $set
  src/__tests__/posthog-core.js
  src/posthog-core.ts
Labels: bump patch

#821 feat: allow regex patterns and wildcards in survey url
  README.md
  src/__tests__/surveys.js
  src/__tests__/utils.js
  src/posthog-surveys-types.ts
  src/posthog-surveys.ts
  src/utils.ts
Labels: bump minor

#822 fix(surveys): multiple choice survey submit button bug
  src/extensions/surveys.ts
Labels: bump patch

#825 fix(surveys): open text value bug
  src/extensions/surveys.ts
Labels: bump patch

#826 feat(surveys): Optional survey questions
  src/extensions/surveys.ts
  src/posthog-surveys-types.ts
Labels: bump minor

#787 fix: Cross-subdomain tracking is not working for long TLDs
  src/storage.ts
Labels: bump patch, stale

#830 feat: Move all logs everything over to logger
  .eslintrc.js
  react/src/context/PostHogProvider.tsx
  src/__tests__/decide.js
  src/__tests__/featureflags.js
  src/__tests__/gdpr-utils.js
  src/__tests__/posthog-core.identify.js
  src/__tests__/posthog-core.js
  src/__tests__/sessionid.js
  src/__tests__/setup.js
  src/autocapture-utils.ts
  src/autocapture.ts
  src/decide.ts
  src/extensions/exceptions/exception-autocapture.ts
  src/extensions/segment-integration.ts
  src/extensions/sessionrecording.ts
  src/extensions/web-performance.ts
  src/gdpr-utils.ts
  src/posthog-core.ts
  src/posthog-featureflags.ts
  src/rate-limiter.ts
  src/retry-queue.ts
  src/sessionid.ts
  src/storage.ts
  src/utils.ts
Labels: bump patch

#840 fix: Fix bot user agent detection
  src/__tests__/utils.js
  src/utils.ts
Labels: bump minor

#841 fix(surveys): fix multiple choice input unique ID bug
  src/__tests__/extensions/surveys.js
  src/extensions/surveys.ts
Labels: bump patch

#842 fix: heroku subdomain check
  src/__tests__/utils.js
  src/posthog-core.ts
  src/utils.ts
Labels: bump patch

#847 fix: full snapshot every 10 minutes
  src/__tests__/extensions/sessionrecording.ts
  src/extensions/sessionrecording.ts
Labels: bump patch

#850 chore: log browser offline status
  src/retry-queue.ts
Labels: bump patch

#839 feat: allow sampling based on decide response
  src/__tests__/extensions/exceptions/error-conversion.test.ts
  src/__tests__/extensions/replay/sessionrecording-utils.test.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/extensions/replay/web-performance.test.ts
  src/__tests__/gdpr-utils.js
  src/__tests__/posthog-persistence.test.ts
  src/__tests__/retry-queue.js
  src/constants.ts
  src/extensions/exceptions/exception-autocapture.ts
  src/extensions/exceptions/stack-trace.ts
  src/extensions/replay/sessionrecording-utils.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/replay/web-performance.ts
  src/extensions/surveys.ts
  src/posthog-core.ts
  src/posthog-featureflags.ts
  src/request-queue.ts
  src/send-request.ts
  src/sessionid.ts
  src/storage.ts
  src/types.ts
  src/utils.ts
  src/uuidv7.ts
Labels: bump minor, you-snizza-bo-logna

#851 fix: Disable the string reduction code until we can battle test it more.
  src/extensions/replay/sessionrecording-utils.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#849 feat: Toolbar loading from state faster
  src/extensions/toolbar.ts
  src/utils.ts
Labels: bump patch

#860 fix: checkout every X minutes
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#831 feat: allow backend to specify a custom analytics endpoint
  src/__tests__/compression.js
  src/__tests__/decide.js
  src/__tests__/posthog-core.js
  src/decide.ts
  src/posthog-core.ts
  src/types.ts
Labels: bump minor

#858 feat(surveys): Make selector targeting work, add user props
  src/__tests__/extensions/surveys.js
  src/extensions/surveys.ts
Labels: bump minor

#861 fix(surveys): clearer user property names
  src/__tests__/extensions/surveys.js
  src/extensions/surveys.ts
Labels: bump patch

#863 fix(surveys): Publish types in module
  src/loader-module.ts
  src/posthog-surveys-types.ts
Labels: bump patch

#864 feat: retry count in url
  .github/workflows/testcafe.yml
  cypress/support/e2e.js
  src/__tests__/__snapshots__/posthog-core.js.snap
  src/__tests__/__snapshots__/send-request.js.snap
  src/__tests__/extensions/exception-autocapture/error-conversion.test.ts
  src/__tests__/gdpr-utils.js
  src/__tests__/posthog-core.js
  src/__tests__/request-utils.test.ts
  src/__tests__/segment.test.ts
  src/__tests__/send-request.js
  src/__tests__/send-request.test.ts
  src/__tests__/utils.js
  src/autocapture-utils.ts
  src/autocapture.ts
  src/decide.ts
  src/extensions/exception-autocapture/error-conversion.ts
  src/extensions/exception-autocapture/index.ts
  src/extensions/exception-autocapture/stack-trace.ts
  src/extensions/exception-autocapture/type-checking.ts
  src/extensions/replay/sessionrecording-utils.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/replay/web-performance.ts
  src/extensions/surveys.ts
  src/extensions/toolbar.ts
  src/gdpr-utils.ts
  src/loader-exception-autocapture.ts
  src/loader-recorder-v2.ts
  src/loader-recorder.ts
  src/loader-surveys.ts
  src/posthog-core.ts
  src/posthog-featureflags.ts
  src/posthog-persistence.ts
  src/posthog-surveys.ts
  src/request-queue.ts
  src/retry-queue.ts
  src/send-request.ts
  src/sessionid.ts
  src/storage.ts
  src/utils/event-utils.ts
  src/utils/index.ts
  src/utils/request-utils.ts
  src/utils/type-utils.ts
  src/uuidv7.ts
Labels: bump patch

#868 fix: include raw user agent in event properties
  src/__tests__/utils.js
  src/__tests__/utils/event-utils.test.ts
  src/utils/event-utils.ts
Labels: bump patch

#870 fix: add tests for browser and browser version detection
  src/__tests__/utils/event-utils.test.ts
  src/utils/event-utils.ts
Labels: bump patch
