Repository PostHog/posthog-js, pull requests merged in 2023-01, with the labels that each got.

#497 feat: capture server timings
  src/extensions/web-performance.ts
Labels: bump patch, lisbon-web-performance

#501 fix: page view ids didn't work with server side config
  src/posthog-core.ts
Labels: bump patch

#499 fix(toolbar): Load toolbar only in body for turbolink
  README.md
  src/autocapture-utils.ts
  src/extensions/toolbar.ts
Labels: bump patch

#503 fix: use django cache for toolbar js
  src/extensions/toolbar.ts
Labels: bump patch

#504 chore: move types dependency from dependencies to devdependencies
  package.json
Labels: bump patch

#506 feat: capture clicked elements on rageclicks
  src/__tests__/autocapture.js
  src/__tests__/extensions/rageclick.js
  src/autocapture.ts
  src/extensions/rageclick.ts
Labels: bump minor

#507 fix: Sentry URL for recording
  src/extensions/sentry-integration.ts
Labels: bump patch

#509 revert: "chore: move types dependency from dependencies to devdependencies"
  package.json
Labels: bump patch

#515 chore: bump to version 1.41.0
  CHANGELOG.md
  package.json
Labels: bump minor

#521 chore: Upgrade to 1.42.1
  CHANGELOG.md
  package.json
Labels: bump patch

#522 chore(feature-flag): only return truthy values for onFeatureFlag
  src/__tests__/featureflags.js
  src/posthog-core.ts
  src/posthog-featureflags.ts
Labels: bump patch
