Repository PostHog/posthog-js, pull requests merged in 2024-02, with the labels that each got.

#985 feat: Fetch without window
  src/__tests__/send-request.test.ts
  src/__tests__/surveys.test.ts
  src/send-request.ts
  src/session-props.ts
  src/utils/event-utils.ts
  src/utils/globals.ts
  src/utils/request-utils.ts
Labels: bump patch

#988 fix: very defensive body redaction
  src/__tests__/extensions/replay/config.test.ts
  src/extensions/replay/config.ts
Labels: bump patch

#996 fix: Remove `baseUrl` from TypeScript compiler options
  src/autocapture-utils.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-utils.ts
  src/rate-limiter.ts
  tsconfig.json
Labels: bump patch

#993 fix: Add warning and conversion for number distinct_id
  functional_tests/identify.test.ts
  src/__tests__/identify.test.ts
  src/posthog-core.ts
Labels: bump minor

#1000 fix: autocapture allowlist should consider the tree
  src/__tests__/autocapture-utils.test.ts
  src/autocapture-utils.ts
  src/types.ts
Labels: bump patch

#1003 fix: mac and github actions don't agree on usable awk variables
  .github/workflows/cd.yml
Labels: bump patch

#1005 feat: save posthog config at start of session recording
  cypress/e2e/session-recording.cy.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1013 fix: allow custom events when idle
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1018 feat: Simplify to just -api and -assets
  src/__tests__/utils/request-router.test.ts
  src/decide.ts
  src/extensions/replay/sessionrecording.ts
  src/posthog-core.ts
  src/posthog-featureflags.ts
  src/utils/request-router.ts
Labels: bump patch

#1022 fix: empty token should be invalid
  src/__tests__/utils/request-router.test.ts
  src/posthog-core.ts
  src/utils/request-router.ts
  src/utils/type-utils.ts
Labels: bump patch

#964 feat(surveys): preact surveys components
  .babelrc
  cypress/e2e/surveys.cy.ts
  package.json
  pnpm-lock.yaml
  rollup.config.js
  src/__tests__/extensions/surveys.js
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys-widget.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/BottomSection.tsx
  src/extensions/surveys/components/ConfirmationMessage.tsx
  src/extensions/surveys/components/PostHogLogo.tsx
  src/extensions/surveys/components/QuestionHeader.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/hooks/useContrastingTextColor.ts
  src/extensions/surveys/icons.tsx
  src/extensions/surveys/surveys-utils.ts
  src/extensions/surveys/surveys-utils.tsx
  src/loader-surveys.ts
  src/posthog-surveys-types.ts
  tsconfig.json
Labels: bump minor

#958 ci: Use GITHUB_OUTPUT envvar instead of set-output command
  .github/workflows/cd.yml
  .github/workflows/label-version-bump.yml
  .github/workflows/new-pr.yml
Labels: stale

#1026 fix: body capture handling
  eslint-rules/no-direct-document-check.js
  eslint-rules/no-direct-file-check.js
  eslint-rules/no-direct-form-data-check.js
  src/__tests__/extensions/replay/config.test.ts
  src/__tests__/request-utils.test.ts
  src/extensions/replay/config.ts
  src/loader-recorder-v2.ts
  src/send-request.ts
  src/types.ts
  src/utils/index.ts
  src/utils/request-utils.ts
  src/utils/type-utils.ts
Labels: bump patch

#1027 fix: protect against parent is not element
  src/__tests__/autocapture-utils.test.ts
  src/autocapture-utils.ts
Labels: bump patch

#1029 fix(surveys): survey popover improvements
  cypress/e2e/surveys.cy.ts
  src/extensions/surveys/surveys-utils.tsx
Labels: bump patch

#1025 feat: Allow changing persistence
  package.json
  playground/nextjs/package.json
  playground/nextjs/pages/_app.tsx
  playground/nextjs/pages/iframe.tsx
  playground/nextjs/pages/index.tsx
  playground/nextjs/pages/long.tsx
  playground/nextjs/pages/longmain.tsx
  playground/nextjs/pnpm-lock.yaml
  playground/nextjs/postcss.config.js
  playground/nextjs/src/CookieBanner.tsx
  playground/nextjs/styles/globals.css
  playground/nextjs/tailwind.config.js
  pnpm-lock.yaml
  react/pnpm-lock.yaml
  src/__tests__/posthog-persistence.test.ts
  src/posthog-core.ts
  src/posthog-persistence.ts
Labels: bump minor

#1030 fix(surveys): Render feedback preview
  cypress/e2e/surveys.cy.ts
  rollup.config.js
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys-widget.ts
  src/extensions/surveys.tsx
  src/loader-surveys-preview.ts
  src/loader-surveys.ts
Labels: bump minor

#1036 fix(surveys): fix emoji scale
  src/extensions/surveys/components/QuestionTypes.tsx
Labels: bump patch

#1037 fix: Path for site apps
  src/decide.ts
Labels: bump patch

#1032 feat: Rollout new ingestion endpoints
  src/__tests__/featureflags.js
  src/__tests__/posthog-core.js
  src/__tests__/surveys.test.ts
  src/__tests__/utils/request-router.test.ts
  src/posthog-core.ts
  src/types.ts
  src/utils/request-router.ts
Labels: bump patch

#1042 fix: Loading the toolbar via JS
  src/extensions/toolbar.ts
Labels: bump patch

#1040 feat: allow linked flag variants to control recording
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/autocapture-utils.ts
  src/extensions/replay/config.ts
  src/extensions/replay/sessionrecording.ts
  src/loader-recorder-v2.ts
  src/types.ts
  src/utils/index.ts
  src/utils/type-utils.ts
Labels: bump minor
