Repository PostHog/posthog-js, pull requests merged in 2024-04, with the labels that each got.

#1102 fix(decide): Respect disable_compression for flags
  src/__tests__/decide.js
  src/__tests__/featureflags.js
  src/decide.ts
  src/posthog-featureflags.ts
Labels: bump patch

#1108 feat: Add __posthog_debug query string
  src/posthog-core.ts
Labels: bump minor

#1113 fix: block bytespider bot
  src/__tests__/utils.test.ts
  src/utils/blocked-uas.ts
Labels: bump patch

#1114 feat: measure identified events
  src/__tests__/posthog-core.js
  src/__tests__/posthog-persistence.test.ts
  src/posthog-persistence.ts
Labels: bump patch

#1104 feat: capture more sentry levels
  src/extensions/sentry-integration.ts
Labels: bump minor

#1117 fix: nextjs playground version of posthog-js
  playground/nextjs/package.json
  playground/nextjs/pnpm-lock.yaml
Labels: bump patch

#1105 feat: allow override sampling
  cypress/e2e/opting-out.cy.ts
  cypress/e2e/session-recording.cy.ts
  cypress/support/assertions.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/constants.ts
  src/extensions/replay/sessionrecording.ts
  src/posthog-core.ts
Labels: bump minor

#1087 fix: Default api host to us.i.posthog.com
  README.md
  playground/nextjs/pages/_app.tsx
  src/__tests__/posthog-core.js
  src/posthog-core.ts
  src/utils/request-router.ts
Labels: bump patch, waiting

#1115 chore: upgrade rrweb to 2.0.0-alpha.12
  package.json
  patches/rrweb@2.0.0-alpha.12.patch
  pnpm-lock.yaml
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1109 feat: Add person processing mode preview
  functional_tests/identify.test.ts
  playground/nextjs/pages/_app.tsx
  src/__tests__/identify.test.ts
  src/__tests__/personProcessing.test.ts
  src/__tests__/posthog-core.js
  src/constants.ts
  src/posthog-core.ts
  src/posthog-persistence.ts
  src/types.ts
  src/utils/event-utils.ts
  src/utils/index.ts
Labels: bump minor

#1120 chore: Add workflow to update the posthog.com repo with new posthog-js versions
  .github/workflows/cd.yml
Labels: bump patch

#1098 fix: Include project token in urls
  src/__tests__/posthog-core.js
  src/extensions/exception-autocapture/index.ts
  src/extensions/sentry-integration.ts
  src/posthog-core.ts
Labels: bump patch

#1122 fix: typing of maskTextFn
  src/types.ts
Labels: bump patch

#1124 feat: Person processing 2 - handle group and setPersonProperties
  playground/nextjs/package.json
  playground/nextjs/pages/_app.tsx
  playground/nextjs/pnpm-lock.yaml
  src/__tests__/personProcessing.test.ts
  src/constants.ts
  src/posthog-core.ts
  src/storage.ts
Labels: bump patch

#1125 fix: missing parentNode protection
  patches/rrweb@2.0.0-alpha.12.patch
  pnpm-lock.yaml
Labels: bump patch

#1123 feat(surveys): Add disable config option
  src/__tests__/decide.js
  src/__tests__/surveys.test.ts
  src/decide.ts
  src/posthog-core.ts
  src/posthog-surveys.ts
  src/types.ts
Labels: bump minor

#1135 fix: continue recording after reset
  cypress/e2e/session-recording.cy.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1134 chore: patch to fix broken worker
  patches/rrweb@2.0.0-alpha.12.patch
  pnpm-lock.yaml
Labels: bump patch

#1126 chore: Autocapture refactor
  cypress/e2e/opting-out.cy.ts
  cypress/e2e/session-recording.cy.ts
  cypress/e2e/surveys.cy.ts
  cypress/support/setup.ts
  playground/session-recordings/server.js
  src/__tests__/autocapture.test.ts
  src/__tests__/decide.js
  src/__tests__/extensions/rageclick.test.ts
  src/__tests__/posthog-core.js
  src/autocapture-utils.ts
  src/autocapture.ts
  src/decide.ts
  src/extensions/rageclick.ts
  src/posthog-core.ts
  src/types.ts
  src/utils/index.ts
Labels: bump patch, heatmaps-in-the-heat

#1118 fix: Allow capturing `aria-label` attribute on sensitive elements
  src/autocapture.ts
Labels: bump minor

#1136 feat: readonly event emitter
  src/posthog-core.ts
  src/utils/simple-event-emitter.ts
Labels: bump minor, heatmaps-in-the-heat

#1141 feat: Rename process_person config option to person_profiles
  src/__tests__/personProcessing.test.ts
  src/__tests__/posthog-core.js
  src/__tests__/posthog-core.test.ts
  src/posthog-core.ts
  src/types.ts
Labels: bump minor

#1119 feat: Update support for segment analytics
  pnpm-lock.yaml
  src/__tests__/segment.test.ts
  src/extensions/segment-integration.ts
  src/posthog-core.ts
  src/types.ts
Labels: bump patch

#1142 chore: update docs on versioning
  README.md
Labels: bump minor

#1143 feat: Rename $process_person to $process_person_profile
  src/__tests__/personProcessing.test.ts
  src/__tests__/posthog-core.js
  src/posthog-core.ts
  src/types.ts
Labels: bump minor

#1138 fix: Reacting to config changes
  cypress/e2e/capture.cy.ts
  playground/nextjs/README.md
  playground/nextjs/package.json
  playground/nextjs/pages/_app.tsx
  playground/nextjs/pages/index.tsx
  playground/nextjs/src/CookieBanner.tsx
  playground/nextjs/src/posthog.ts
  src/__tests__/autocapture.test.ts
  src/__tests__/decide.js
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/helpers/script-utils.ts
  src/__tests__/posthog-core.js
  src/__tests__/surveys.test.ts
  src/autocapture.ts
  src/decide.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/toolbar.ts
  src/posthog-core.ts
  src/posthog-surveys.ts
Labels: bump minor

#1051 feat: Added client side capture rate limiting
  src/__tests__/posthog-core.identify.js
  src/__tests__/posthog-core.js
  src/__tests__/posthog-persistence.test.ts
  src/__tests__/rate-limiter.test.ts
  src/constants.ts
  src/extensions/segment-integration.ts
  src/posthog-core.ts
  src/posthog-persistence.ts
  src/rate-limiter.ts
  src/types.ts
Labels: bump minor, waiting

#1131 feat: Heatmaps instrumentation
  playground/nextjs/pages/index.tsx
  playground/nextjs/src/posthog.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/heatmaps.test.ts
  src/__tests__/page-view.test.ts
  src/__tests__/posthog-core.js
  src/autocapture-utils.ts
  src/autocapture.ts
  src/extensions/exception-autocapture/index.ts
  src/extensions/replay/sessionrecording.ts
  src/heatmaps.ts
  src/page-view.ts
  src/posthog-core.ts
  src/scroll-manager.ts
  src/types.ts
Labels: bump minor, heatmaps-in-the-heat

#1140 fix: Remove underscores from all functions
  cypress/e2e/session-recording.cy.ts
  eslint-rules/README.md
  eslint-rules/custom-eslint-rules.test.js
  eslint-rules/no-direct-array-check.js
  eslint-rules/no-direct-boolean-check.js
  eslint-rules/no-direct-date-check.js
  eslint-rules/no-direct-document-check.js
  eslint-rules/no-direct-file-check.js
  eslint-rules/no-direct-form-data-check.js
  eslint-rules/no-direct-function-check.js
  eslint-rules/no-direct-null-check.js
  eslint-rules/no-direct-number-check.js
  eslint-rules/no-direct-object-check.js
  eslint-rules/no-direct-string-check.js
  eslint-rules/no-direct-undefined-check.js
  src/__tests__/extensions/exception-autocapture/error-conversion.test.ts
  src/__tests__/extensions/toolbar.test.ts
  src/__tests__/gdpr-utils.test.ts
  src/__tests__/posthog-core.js
  src/__tests__/request-utils.test.ts
  src/__tests__/utils.test.ts
  src/__tests__/utils/event-utils.test.ts
  src/autocapture-utils.ts
  src/autocapture.ts
  src/decide.ts
  src/extensions/exception-autocapture/error-conversion.ts
  src/extensions/exception-autocapture/index.ts
  src/extensions/exception-autocapture/stack-trace.ts
  src/extensions/exception-autocapture/type-checking.ts
  src/extensions/replay/config.ts
  src/extensions/replay/sessionrecording-utils.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/segment-integration.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/toolbar.ts
  src/gdpr-utils.ts
  src/heatmaps.ts
  src/loader-recorder.ts
  src/page-view.ts
  src/posthog-core.ts
  src/posthog-featureflags.ts
  src/posthog-persistence.ts
  src/posthog-surveys.ts
  src/request-queue.ts
  src/request.ts
  src/retry-queue.ts
  src/scroll-manager.ts
  src/session-props.ts
  src/sessionid.ts
  src/storage.ts
  src/utils/blocked-uas.ts
  src/utils/event-utils.ts
  src/utils/index.ts
  src/utils/logger.ts
  src/utils/request-utils.ts
  src/utils/type-utils.ts
  src/utils/user-agent-utils.ts
  src/uuidv7.ts
Labels: bump patch

#1145 feat: add deepscan agent
  src/utils/blocked-uas.ts
Labels: bump patch

#1149 chore: upgrade rrweb to alpha-13
  package.json
  patches/rrweb@2.0.0-alpha.11.patch
  patches/rrweb@2.0.0-alpha.13.patch
  pnpm-lock.yaml
Labels: bump patch

#1152 fix: Don't track heatmaps of toolbar
  src/__tests__/heatmaps.test.ts
  src/heatmaps.ts
Labels: bump patch

#1153 chore: Fix duplicate string
  src/heatmaps.ts
Labels: bump patch

#1154 feat: Remotely enable heatmaps via decide
  src/__tests__/heatmaps.test.ts
  src/constants.ts
  src/heatmaps.ts
  src/posthog-core.ts
  src/types.ts
Labels: bump minor

#1156 feat: Move heatmaps out of preview
  playground/nextjs/src/posthog.ts
  src/__tests__/heatmaps.test.ts
  src/heatmaps.ts
  src/types.ts
Labels: bump minor

#1157 fix(surveys): use correct render method
  src/extensions/surveys.tsx
Labels: bump patch
