Repository PostHog/posthog-js, pull requests merged in 2024-10, with the labels that each got.

#1445 feat: default replay partial compression on
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
  src/types.ts
Labels: bump minor

#1446 fix: skip addition of `src` attribute for HLS videos
  patches/rrweb@2.0.0-alpha.13.patch
  playground/nextjs/package.json
  playground/nextjs/pages/replay-examples/media.tsx
  playground/nextjs/pnpm-lock.yaml
  pnpm-lock.yaml
Labels: bump patch

#1454 fix: Remove posthog error capture from replay
  src/extensions/replay/sessionrecording-utils.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1443 feat(web experiments): Emit web_experiment_applied event and do not render experiments for bots
  playground/nextjs/pages/index.tsx
  playground/nextjs/src/posthog.ts
  src/__tests__/web-experiments.test.ts
  src/web-experiments-types.ts
  src/web-experiments.ts
Labels: bump minor

#1452 feat: report reason for recording start
  cypress/e2e/session-recording.cy.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
  src/posthog-core.ts
Labels: bump minor, stale

#1475 chore: skip if Array.from is missing
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1474 fix: web vitals delayed capture
  src/__tests__/extensions/web-vitals.test.ts
  src/extensions/web-vitals/index.ts
  src/types.ts
Labels: bump minor

#1451 feat: start session recording on url trigger
  src/constants.ts
  src/extensions/replay/sessionrecording.ts
  src/types.ts
Labels: bump minor

#1480 chore: build an es5 bundle and move main to es6
  .babelrc
  .github/workflows/es-check.yml
  package.json
  pnpm-lock.yaml
  rollup.config.js
  src/entrypoints/array.full.es5.ts
  testcafe/helpers.js
Labels: bump minor

#1481 chore: add crossOrigin='anonymous' to snippet script
  playground/cypress-full/index.html
  playground/cypress/index.html
  playground/segment/segment.html
  playground/session-recordings/index.html
  playground/snippet/index.html
  src/entrypoints/external-scripts-loader.ts
Labels: bump patch

#1482 feat(web-analytics): Store nulls for unset campaign params
  src/__tests__/personProcessing.test.ts
  src/utils/event-utils.ts
Labels: bump minor

#1473 feat(surveys): Make entire cancel button area clickable
  src/extensions/surveys/components/QuestionHeader.tsx
Labels: bump minor

#1483 fix: do not capture entire elements in web vitals
  src/extensions/web-vitals/index.ts
Labels: bump patch

#1486 fix: no need to swallow import errors
  src/entrypoints/recorder.ts
Labels: bump patch

#1276 chore: upgrade rrweb to alpha.16
  package.json
  patches/rrweb@2.0.0-alpha.13.patch
  patches/rrweb@2.0.0-alpha.16.patch
  playground/segment/server.js
  pnpm-lock.yaml
  src/entrypoints/recorder.ts
Labels: bump patch

#1491 fix: expose the last activity timestamp in session id check result
  src/__tests__/sessionid.test.ts
  src/sessionid.ts
Labels: bump patch

#1496 fix: allow canvas local config
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/utils/number-utils.test.ts
  src/extensions/replay/sessionrecording.ts
  src/page-view.ts
  src/sessionid.ts
  src/types.ts
  src/utils/index.ts
  src/utils/number-utils.ts
Labels: bump minor

#1495 chore: set platform on stack frame
  src/extensions/exception-autocapture/stack-trace.ts
Labels: bump patch

#1494 fix(surveys): Reset Survey storage after posthog.reset is called
  src/__tests__/surveys.test.ts
  src/extensions/surveys/surveys-utils.tsx
  src/posthog-core.ts
  src/posthog-surveys.ts
Labels: bump minor

#1456 fix: empty query param when calling external dependency toolbar.js
  src/__tests__/utils/external-scripts-loader.test.ts
  src/entrypoints/external-scripts-loader.ts
Labels: bump patch

#1501 fix: reduce keep alive threshold
  src/request.ts
Labels: bump patch

#1493 feat: Only set missing campaign params to null if there is at least one non-null
  src/__tests__/posthog-core.test.ts
  src/posthog-persistence.ts
Labels: bump minor

#1504 feat: Add timezone to events
  src/utils/event-utils.ts
Labels: bump minor

#1506 feat: allow mutation rate limiter configuration
  src/extensions/replay/mutation-rate-limiter.ts
  src/extensions/replay/sessionrecording.ts
  src/types.ts
Labels: bump minor
