Repository PostHog/posthog-js, pull requests merged in 2024-06, with the labels that each got.

#1218 fix: heatmaps with segment integration
  src/posthog-core.ts
Labels: bump patch

#1215 fix: do not start recording buffer without id
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1217 feat: add an explicit in-memory buffer
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1214 chore(surveys): refactor survey popup (vol. 1)
  playground/vite-surveys/src/list.tsx
  src/__tests__/extensions/surveys.test.ts
  src/__tests__/surveys.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/BottomSection.tsx
  src/extensions/surveys/components/ConfirmationMessage.tsx
  src/extensions/surveys/components/QuestionHeader.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/surveys-utils.tsx
  src/posthog-surveys-types.ts
Labels: bump patch

#1222 fix: no full snapshot while idle
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1225 fix: flush on idle
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1227 chore: Bump version to 1.137.0
  CHANGELOG.md
Labels: bump minor

#1206 feat(surveys): `posthog-js` changes to support valid HTML question rendering
  cypress/e2e/surveys.cy.ts
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/ConfirmationMessage.tsx
  src/extensions/surveys/components/QuestionHeader.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/surveys-utils.tsx
  src/posthog-surveys-types.ts
Labels: bump minor

#1186 feat: wrap fetch and add tracing headers
  rollup.config.js
  src/extensions/replay/rrweb-plugins/patch.ts
  src/extensions/tracing-headers.ts
  src/loader-recorder.ts
  src/loader-tracing-headers.ts
  src/posthog-core.ts
  src/types.ts
Labels: bump patch, mykologs

#1224 feat: Updated v8 sentry integration
  package.json
  pnpm-lock.yaml
  src/extensions/sentry-integration.ts
  src/posthog-core.ts
Labels: bump patch

#1230 fix: circular refs shouldn't explode capture
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1236 feat(personless-events): set_once more initial properties accurately when a person is created
  src/__tests__/personProcessing.test.ts
  src/__tests__/posthog-core.js
  src/constants.ts
  src/posthog-core.ts
  src/posthog-persistence.ts
  src/utils/event-utils.ts
Labels: bump minor

#1241 fix: less strict idle event dropping
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1219 feat: allow not operators in survey url targeting
  src/__tests__/surveys.test.ts
  src/posthog-surveys-types.ts
  src/posthog-surveys.ts
Labels: bump minor

#1245 fix: only wrap once when patching
  src/__tests__/extensions/replay/rrweb-plugins/patch.test.ts
  src/loader-recorder.ts
Labels: bump patch

#1247 feat(surveys): add branching logic
  src/__tests__/surveys.test.ts
  src/extensions/surveys.tsx
  src/posthog-core.ts
  src/posthog-surveys-types.ts
  src/posthog-surveys.ts
Labels: bump patch

#1254 fix: no scheduled snapshots while idle
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
  src/types.ts
Labels: bump patch

#1250 fix: Allow no capture of $opt_in event
  src/__tests__/consent.test.ts
  src/posthog-core.ts
Labels: bump patch

#1260 fix(surveys): handle missing getNextSurveyStep
  src/extensions/surveys.tsx
Labels: bump patch

#1263 fix(surveys): fix missing confirmation message state
  src/extensions/surveys.tsx
Labels: bump patch

#1257 fix(surveys branching): rename confirmation_message -> end
  src/__tests__/surveys.test.ts
  src/extensions/surveys.tsx
  src/posthog-core.ts
  src/posthog-surveys-types.ts
  src/posthog-surveys.ts
Labels: bump patch

#1259 feat(web-analytics): Add property for autocapture link click
  playground/nextjs/pages/index.tsx
  src/__tests__/autocapture.test.ts
  src/autocapture.ts
Labels: bump minor

#1267 fix: unwind recent changes things seem less stable
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1228 feat(surveys): add configurable delay to popup surveys
  package.json
  pnpm-lock.yaml
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/posthog-surveys-types.ts
Labels: bump minor

#1261 fix: exception autocapture
  cypress/e2e/error-tracking.cy.ts
  cypress/support/e2e.ts
  playground/cypress/index.html
  src/__tests__/extensions/exception-autocapture/error-conversion.test.ts
  src/__tests__/extensions/exception-autocapture/exception-observer.test.ts
  src/constants.ts
  src/decide.ts
  src/extensions/exception-autocapture/error-conversion.ts
  src/extensions/exception-autocapture/index.ts
  src/extensions/sentry-integration.ts
  src/loader-exception-autocapture.ts
  src/posthog-core.ts
  src/types.ts
Labels: bump patch

#1203 feat: add lazily loaded web vitals collection
  package.json
  pnpm-lock.yaml
  rollup.config.js
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/posthog-core.test.ts
  src/__tests__/web-vitals.test.ts
  src/constants.ts
  src/decide.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/web-vitals/index.ts
  src/heatmaps.ts
  src/loader-web-vitals.ts
  src/posthog-core.ts
  src/types.ts
  testcafe/helpers.js
Labels: bump patch

#1272 fix: dropped styles on route transition
  patches/rrweb@2.0.0-alpha.13.patch
  pnpm-lock.yaml
Labels: bump patch

#1275 fix: use includes over contains
  patches/rrweb@2.0.0-alpha.13.patch
  pnpm-lock.yaml
Labels: bump patch

#1277 feat: warn when distinct id invalid for replay
  src/posthog-core.ts
Labels: bump patch
