Repository PostHog/posthog-js, pull requests merged in 2024-03, with the labels that each got.

#1047 feat: copy and cut autocapture
  playground/selection-autocapture/demo.html
  src/__tests__/autocapture.test.ts
  src/autocapture-utils.ts
  src/autocapture.ts
  src/types.ts
Labels: bump minor

#1052 chore: Removed jsc callbacks
  src/__tests__/autocapture.test.ts
  src/__tests__/decide.js
  src/__tests__/featureflags.js
  src/__tests__/surveys.test.ts
  src/posthog-core.ts
  src/posthog-featureflags.ts
  src/types.ts
Labels: bump patch

#1049 feat: Ensure ingestion domains follow the same logic.
  src/__tests__/utils/request-router.test.ts
  src/utils/request-router.ts
Labels: bump patch

#1023 chore: Rework SDK initialisation
  playground/session-recordings/index.html
  src/__tests__/helpers/posthog-instance.ts
  src/__tests__/loader.test.ts
  src/__tests__/posthog-core.identify.js
  src/__tests__/posthog-core.js
  src/posthog-core.ts
Labels: bump patch, waiting

#1062 fix: Choice of capture compression
  src/posthog-core.ts
  src/types.ts
Labels: bump patch

#1059 feat: scrub payloads with forbidden words
  src/__tests__/extensions/replay/config.test.ts
  src/autocapture-utils.ts
  src/extensions/replay/config.ts
Labels: bump minor

#1069 fix: clarify redaction message
  src/__tests__/extensions/replay/config.test.ts
  src/extensions/replay/config.ts
Labels: bump patch

#1068 fix: Send beacon request encoding
  src/__tests__/request.test.ts
  src/request.ts
  src/utils/globals.ts
Labels: bump patch

#1072 fix(posthog-js): manually bump patch
  package.json
Labels: bump patch

#1071 feat: report browser visibility state in replay
  src/extensions/replay/sessionrecording.ts
Labels: bump minor

#1074 fix: Disabled compression and application json
  cypress/support/compression.ts
  functional_tests/mock-server.ts
  src/__tests__/request.test.ts
  src/posthog-core.ts
  src/request.ts
Labels: bump patch

#1075 fix: patch rrweb zero width canvas bug
  patches/rrweb@2.0.0-alpha.11.patch
  pnpm-lock.yaml
Labels: bump patch

#1076 feat: track recording URL without pageview capture
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump minor

#1082 fix: canvas recording patches
  patches/rrweb@2.0.0-alpha.11.patch
  pnpm-lock.yaml
Labels: bump patch

#1085 fix: allow payload scrubbing override
  src/__tests__/extensions/replay/config.test.ts
  src/extensions/replay/config.ts
Labels: bump minor

#1080 chore: Remove v2 rrweb checks
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/posthog-core.js
  src/extensions/replay/sessionrecording.ts
  src/posthog-core.ts
Labels: bump patch

#1084 feat: add property so we can check if a client is using a proxy
  src/__tests__/posthog-core.js
  src/posthog-core.ts
Labels: bump patch

#1092 fix: Return this if already loaded
  src/__tests__/loader.test.ts
  src/posthog-core.ts
Labels: bump patch

#1094 fix: custom event on sampling decision
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1097 fix: posthog init should reject invalid config in TypeScript
  src/posthog-core.ts
  src/types.ts
Labels: bump patch

#1095 fix: Reloading toolbar after closing
  src/__tests__/extensions/toolbar.test.ts
  src/extensions/toolbar.ts
Labels: bump patch
