Repository PostHog/posthog-js, pull requests merged in 2024-11, with the labels that each got.

#1508 fix: dead click fixes from watching in prod
  src/__tests__/entrypoints/lazy-loaded-dead-clicks-autocapture.test.ts
  src/autocapture-utils.ts
  src/autocapture.ts
  src/entrypoints/dead-clicks-autocapture.ts
  src/heatmaps.ts
  src/utils/element-utils.ts
Labels: bump patch

#1511 chore: add stack type
  src/extensions/exception-autocapture/error-conversion.ts
Labels: bump minor

#1489 chore: upgrade rrweb to alpha.17
  package.json
  patches/@rrweb__record@2.0.0-alpha.17.patch
  patches/@rrweb__rrweb-plugin-console-record@2.0.0-alpha.17.patch
  patches/rrweb@2.0.0-alpha.16.patch
  pnpm-lock.yaml
  src/__tests__/extensions/replay/mutation-rate-limiter.test.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/entrypoints/recorder.ts
  src/extensions/replay/sessionrecording-utils.ts
  src/extensions/replay/sessionrecording.ts
  src/types.ts
  src/utils/globals.ts
Labels: bump minor

#1500 feat: add recording url blocklist
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
  src/types.ts
Labels: bump minor

#1510 feat: deadclicks in heatmaps
  src/__tests__/entrypoints/lazy-loaded-dead-clicks-autocapture.test.ts
  src/__tests__/extensions/dead-clicks-autocapture.test.ts
  src/__tests__/heatmaps.test.ts
  src/constants.ts
  src/entrypoints/dead-clicks-autocapture.ts
  src/extensions/dead-clicks-autocapture.ts
  src/heatmaps.ts
  src/posthog-core.ts
  src/types.ts
  src/utils/element-utils.ts
  src/utils/globals.ts
Labels: bump minor

#1520 chore: add type to Sentry exception
  cypress/e2e/error-tracking.cy.ts
  src/extensions/sentry-integration.ts
Labels: bump patch

#1516 fix(flags): support multiple children prop in PostHogFeature
  react/src/components/PostHogFeature.tsx
  react/src/components/__tests__/PostHogFeature.test.jsx
  react/src/utils/type-utils.ts
Labels: bump patch

#1517 feat: Add customization to add all person profile properties as setPersonPropertiesForFlags
  playground/nextjs/pages/index.tsx
  src/__tests__/customizations/setAllPersonProfilePropertiesAsPersonPropertiesForFlags.test.ts
  src/config.ts
  src/customizations/setAllPersonProfilePropertiesAsPersonPropertiesForFlags.ts
  src/utils/event-utils.ts
Labels: bump minor

#1523 feat: allow triggering sessions when events occur
  cypress/e2e/session-recording.cy.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/constants.ts
  src/extensions/replay/sessionrecording.ts
  src/posthog-core.ts
  src/types.ts
Labels: bump minor

#1527 fix: XHR req method capture
  cypress/e2e/session-recording.cy.ts
  playground/cypress/index.html
  src/entrypoints/recorder.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1531 fix: angular change detection mutation observer
  eslint-rules/no-direct-mutation-observer.js
  src/entrypoints/dead-clicks-autocapture.ts
  src/utils/globals.ts
  src/utils/prototype-utils.ts
  src/utils/type-utils.ts
Labels: bump patch

#1535 fix: refactor native mutation observer implementation
  src/entrypoints/dead-clicks-autocapture.ts
  src/utils/globals.ts
  src/utils/type-utils.ts
Labels: bump patch

#1515 feat: allow config of before_send function to edit or reject events
  cypress/e2e/before_send.cy.ts
  cypress/support/commands.ts
  playground/copy-autocapture/demo.html
  src/__tests__/autocapture.test.ts
  src/__tests__/consent.test.ts
  src/__tests__/extensions/exception-autocapture/exception-observer.test.ts
  src/__tests__/extensions/web-vitals.test.ts
  src/__tests__/heatmaps.test.ts
  src/__tests__/identify.test.ts
  src/__tests__/personProcessing.test.ts
  src/__tests__/posthog-core.beforeSend.test.ts
  src/__tests__/posthog-core.identify.test.ts
  src/__tests__/posthog-core.test.ts
  src/__tests__/posthog-core.ts
  src/__tests__/utils/before-send-utils.test.ts
  src/autocapture.ts
  src/customizations/before-send.ts
  src/posthog-core.ts
  src/types.ts
  src/utils/type-utils.ts
  testcafe/helpers.js
Labels: bump minor

#1543 fix: patch angular wrap detection in rrweb
  patches/@rrweb__record@2.0.0-alpha.17.patch
  pnpm-lock.yaml
Labels: bump patch

#1542 fix: improve ES6 bundling
  .github/workflows/es-check.yml
  rollup.config.js
  src/__tests__/posthog-core.test.ts
Labels: bump patch

#1548 fix(surveys): Process feature_flag_keys on Survey object
  src/__tests__/surveys.test.ts
  src/posthog-surveys-types.ts
  src/posthog-surveys.ts
Labels: bump minor

#1553 fix: safari support requires we don't use
  src/extensions/replay/sessionrecording-utils.ts
Labels: bump patch

#1546 feat: hog site functions
  src/__tests__/decide.ts
  src/__tests__/entrypoints/lazy-loaded-dead-clicks-autocapture.test.ts
  src/__tests__/posthog-persistence.test.ts
  src/__tests__/site-apps.ts
  src/autocapture.ts
  src/decide.ts
  src/posthog-core.ts
  src/site-apps.ts
  src/types.ts
Labels: bump patch

#1559 feat: Add initial person info to cookie when using localPlusCookieStore
  src/__tests__/personProcessing.test.ts
  src/__tests__/posthog-persistence.test.ts
  src/storage.ts
  src/utils/event-utils.ts
Labels: bump minor

#1562 fix: catch errors detecting dialog state when recording
  patches/@rrweb__record@2.0.0-alpha.17.patch
  pnpm-lock.yaml
Labels: bump patch

#1566 fix: patch to angular detection in rrweb
  patches/@rrweb__record@2.0.0-alpha.17.patch
  pnpm-lock.yaml
Labels: bump patch

#1558 feat: different default and max idle period
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/sessionid.test.ts
  src/__tests__/utils/number-utils.test.ts
  src/posthog-core.ts
  src/sessionid.ts
  src/utils/number-utils.ts
Labels: bump minor

#1568 feat: Start tracking timezone offset and language prefix
  src/__tests__/utils/event-utils.test.ts
  src/utils/event-utils.ts
Labels: bump minor, feature/web-analytics

#1569 fix: infinite loop when combining controls
  cypress/e2e/session-recording.cy.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1509 feat: allow decide to provide script name for recorder
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/constants.ts
  src/extensions/replay/sessionrecording.ts
  src/types.ts
Labels: bump minor

#1570 fix: zone detection
  patches/@rrweb__record@2.0.0-alpha.17.patch
  pnpm-lock.yaml
  src/utils/prototype-utils.ts
  src/utils/type-utils.ts
Labels: bump patch

#1571 feat: add $recording_status property
  src/__tests__/posthog-core.ts
  src/extensions/replay/sessionrecording.ts
  src/posthog-core.ts
Labels: bump minor

#1573 fix: Don't crash on bigints
  src/__tests__/request.test.ts
  src/request.ts
Labels: bump patch
