Repository PostHog/posthog-js, pull requests merged in 2024-09, with the labels that each got.

#1386 fix: report requests even without timing
  src/entrypoints/recorder.ts
Labels: bump patch

#1398 fix: captured network requests must always have name property
  src/entrypoints/recorder.ts
Labels: bump patch

#1401 feat: web vitals 3000
  src/__tests__/extensions/web-vitals.test.ts
  src/constants.ts
  src/entrypoints/web-vitals.ts
  src/extensions/web-vitals/index.ts
  src/types.ts
Labels: bump minor

#1400 fix: warn on unavailable lazy load not throw
  src/posthog-surveys.ts
Labels: bump patch

#1406 fix: some clients need web vitals directly on window
  src/entrypoints/web-vitals.ts
Labels: bump patch

#1408 fix: manage capture pageview hook lifecycle
  cypress/e2e/session-recording.cy.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
  src/posthog-core.ts
Labels: bump patch

#1416 fix: no keep alive for large payloads
  src/__tests__/request.test.ts
  src/request.ts
Labels: bump patch

#1411 fix: teardown and restart recording on session id change
  cypress/e2e/session-recording.cy.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/posthog-core.identify.test.ts
  src/__tests__/sessionid.test.ts
  src/extensions/replay/sessionrecording.ts
  src/sessionid.ts
  src/types.ts
Labels: bump patch

#1422 fix: when capturing without performance entry we can capture manual initiator type
  src/entrypoints/recorder.ts
Labels: bump patch

#1424 fix(surveys): 7-point likert scale didn't work with branching logic
  src/__tests__/surveys.test.ts
  src/posthog-surveys.ts
Labels: bump minor

#1407 feat: type safe posthog extensions
  .github/workflows/label-alpha-release.yml
  src/__tests__/extensions/exception-autocapture/exception-observer.test.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/surveys.test.ts
  src/entrypoints/exception-autocapture.ts
  src/entrypoints/recorder.ts
  src/entrypoints/surveys.ts
  src/entrypoints/tracing-headers.ts
  src/extensions/exception-autocapture/index.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/tracing-headers.ts
  src/extensions/web-vitals/index.ts
  src/posthog-core.ts
  src/posthog-surveys.ts
  src/utils/globals.ts
Labels: bump minor, release alpha

#1428 fix: session idle timestamp correction
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1430 chore: build when publishing
  package.json
Labels: bump patch

#1433 fix: get computed style error
  src/autocapture-utils.ts
  src/autocapture.ts
  src/heatmaps.ts
Labels: bump patch

#1436 feat: compress replay data
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
  src/types.ts
Labels: bump minor

#1438 fix: no custom events when idle
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
  src/sessionid.ts
  src/types.ts
Labels: bump patch
