Repository PostHog/posthog-js, pull requests merged in 2025-07, with the labels that each got.

#2074 fix: Fix backwards compatibility
  packages/browser/src/extensions/surveys.tsx
Labels: bump patch

#2081 feat(err): return capture results from captureException
  packages/browser/src/posthog-core.ts
  packages/browser/src/posthog-exceptions.ts
Labels: bump patch, stale

#2114 chore(ci): install before calling changeset
  .github/workflows/label-version-bump.yml
Labels: release

#2118 chore(ci): fix react peer dependencies
  .changeset/config.json
  .github/workflows/label-version-bump.yml
  packages/browser/CHANGELOG.md
  packages/react/package.json
Labels: release

#2091 chore: only evaluate display logic for in-app surveys
  packages/browser/rollup.config.mjs
  packages/browser/src/__tests__/posthog-surveys.test.ts
  packages/browser/src/__tests__/surveys.test.ts
  packages/browser/src/extensions/surveys.tsx
  packages/browser/src/posthog-surveys-types.ts
  packages/browser/src/posthog-surveys.ts
  packages/browser/src/utils/survey-utils.ts
  packages/browser/terser-mangled-names.json
Labels: bump patch, feature/surveys

#2111 fix: mark as idle only when definitely idle
  .changeset/lucky-sheep-create.md
  packages/browser/src/__tests__/sessionid.test.ts
  packages/browser/src/sessionid.ts
  packages/browser/terser-mangled-names.json
Labels: release

#2172 chore: add new enable surveys config
  .changeset/four-dolls-boil.md
  packages/browser/package.json
  packages/browser/src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  packages/browser/src/posthog-core.ts
  packages/browser/src/posthog-surveys.ts
  packages/browser/src/types.ts
Labels: feature/surveys, release
