Repository PostHog/posthog-js, pull requests merged in 2025-04, with the labels that each got.

#1856 fix: focus open input field on choice click
  src/__tests__/extensions/surveys/question-types.test.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
Labels: bump patch

#1857 fix: return can render survey reason
  playground/nextjs/pages/survey.tsx
  src/posthog-core.ts
  src/posthog-surveys.ts
Labels: bump patch, feature/surveys

#1863 fix: clean styles to prevent <br> tags
  src/extensions/surveys/surveys-utils.tsx
Labels: bump patch

#1865 fix: survey feedback button anchoring to trigger
  src/extensions/surveys.tsx
Labels: bump patch, feature/surveys

#1873 feat: Only capture vitals on http and https
  src/__tests__/extensions/web-vitals.test.ts
  src/extensions/web-vitals/index.ts
Labels: bump patch

#1877 fix: make survey widget with selector work with SPAs
  playground/nextjs/pages/survey.tsx
  playground/react-router/package.json
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys.tsx
  src/posthog-surveys-types.ts
  src/utils/index.ts
Labels: bump minor

#1887 chore: even more replay debug signal
  playwright/session-recording/session-recording.spec.ts
  src/__tests__/posthog-core.ts
  src/extensions/replay/sessionrecording.ts
  src/posthog-core.ts
Labels: bump patch

#1885 fix: new survey position for feedback button
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-utils.tsx
  src/posthog-surveys-types.ts
Labels: bump patch, feature/surveys

#1890 fix: web vitals running when capture_performance: false is set
  src/__tests__/extensions/web-vitals.test.ts
  src/extensions/web-vitals/index.ts
Labels: bump patch

#1892 fix: survey feedback button not showing after url change
  src/__tests__/extensions/surveys.test.ts
  src/__tests__/extensions/surveys/feedback-widget.test.tsx
  src/extensions/surveys-widget.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/QuestionHeader.tsx
Labels: bump patch, feature/surveys

#1893 feat: Improve how PostHogProvider works with SSR
  react/src/context/PostHogProvider.tsx
Labels: bump patch

#1891 chore: add canRenderSurveyAsync
  src/__tests__/surveys.test.ts
  src/posthog-core.ts
  src/posthog-surveys.ts
Labels: bump minor

#1903 chore: refactor survey loadIfEnabled
  src/posthog-surveys.ts
Labels: bump patch, feature/surveys

#1907 fix: Fix response based branching for open choice questions
  src/__tests__/surveys.test.ts
  src/extensions/surveys.tsx
Labels: bump patch

#1908 fix: timezone offset property not being sent
  src/__tests__/utils/event-utils.test.ts
  src/utils/index.ts
Labels: bump patch

#1912 fix: prevent multiple stylesheet creation for feedback survey
  src/extensions/surveys.tsx
Labels: bump patch, feature/surveys

#1911 fix: dont propagate events in surveys
  src/__tests__/extensions/surveys/question-types.test.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
Labels: bump patch, feature/surveys

#1704 fix: make feedback tab survey display responsive
  playwright/surveys/feedback-widget.spec.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-extension-utils.tsx
Labels: bump patch, feature/surveys

#1897 fix: refactor canRenderSurvey and move logic to SurveyManager
  playground/nextjs/pages/_app.tsx
  playground/react-router/app/root.tsx
  src/__tests__/extensions/surveys-utils.test.ts
  src/__tests__/extensions/surveys.test.ts
  src/__tests__/posthog-surveys.test.ts
  src/__tests__/surveys.test.ts
  src/extensions/segment-integration.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-extension-utils.tsx
  src/posthog-core.ts
  src/posthog-surveys.ts
  src/utils/survey-event-receiver.ts
  src/utils/survey-utils.ts
Labels: bump patch, feature/surveys

#1921 chore: survey 10kb win
  src/extensions/surveys/surveys-extension-utils.tsx
  src/posthog-surveys-types.ts
  src/posthog-surveys.ts
  src/utils/survey-utils.ts
Labels: bump patch, feature/surveys

#1902 feat: Reduce bundle size with property mangling
  .github/workflows/library-ci.yml
  package.json
  rollup.config.js
  src/posthog-core.ts
  src/utils/globals.ts
  terser-mangled-names.json
Labels: bump patch

#1924 fix: prevent survey events to affect multiple surveys
  package.json
  playwright/surveys/core-display-logic.spec.ts
  playwright/surveys/customization.spec.ts
  playwright/surveys/feedback-widget.spec.ts
  playwright/surveys/question-types.spec.ts
  playwright/surveys/response-capture.spec.ts
  playwright/surveys/thank-you-message.spec.ts
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys-widget.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-extension-utils.tsx
Labels: bump minor, feature/surveys

#1926 chore: use getConstratingColor and add question-container
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/hooks/useContrastingTextColor.ts
  src/extensions/surveys/surveys-extension-utils.tsx
Labels: bump patch
