Repository PostHog/posthog-js, pull requests merged in 2025-09, with the labels that each got.

#2253 feat(llma): support-openai-embeddings
  .changeset/true-rings-doubt.md
  .eslintrc.cjs
  packages/ai/.eslintrc.cjs
  packages/ai/src/anthropic/index.ts
  packages/ai/src/gemini/index.ts
  packages/ai/src/langchain/callbacks.ts
  packages/ai/src/openai/azure.ts
  packages/ai/src/openai/index.ts
  packages/ai/src/utils.ts
  packages/ai/src/vercel/middleware.ts
  packages/ai/tests/azure-openai.test.ts
  packages/ai/tests/openai.test.ts
  packages/ai/tests/vercel.test.ts
Labels: release

#2259 feat: add unused lazy loading recorder
  packages/browser/src/entrypoints/lazy-recorder.ts
  packages/browser/src/extensions/replay/external/lazy-loaded-session-recorder.ts
  packages/browser/src/extensions/replay/sessionrecording.ts
  packages/browser/src/types.ts
  packages/browser/src/utils/globals.ts
  packages/browser/terser-mangled-names.json
Labels: bump patch

#2264 chore: bump version
  .changeset/silly-paws-beam.md
Labels: release

#2266 fix: don't mangle to $
  .changeset/clever-rings-itch.md
  packages/browser/rollup.config.mjs
Labels: release

#2267 feat: allow opting in to testing session replay code lazy loading
  .changeset/heavy-ravens-own.md
  packages/browser/src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  packages/browser/src/entrypoints/posthog-recorder.ts
  packages/browser/src/extensions/replay/sessionrecording-wrapper.ts
  packages/browser/src/extensions/replay/triggerMatching.ts
  packages/browser/src/posthog-core.ts
  packages/browser/src/types.ts
  packages/browser/terser-mangled-names.json
Labels: release

#2275 fix(err): upgrade posthog/cli version
  .changeset/slick-spoons-search.md
  packages/nextjs-config/package.json
  pnpm-lock.yaml
Labels: release

#2272 fix: dynamically extract posthog params from OpenAI calls
  .changeset/slow-foxes-kneel.md
  packages/ai/src/openai/azure.ts
  packages/ai/src/openai/index.ts
  packages/ai/src/openai/utils.ts
  packages/ai/src/utils.ts
  packages/ai/tests/azure-openai.test.ts
  packages/ai/tests/openai.test.ts
Labels: release

#2284 fix: order of operations when replay does pageview fallback
  .changeset/stale-taxes-unite.md
  packages/browser/src/__tests__/segment.test.ts
  packages/browser/src/extensions/replay/external/lazy-loaded-session-recorder.ts
Labels: release

#2276 fix(flags): `isFeatureEnabled` discerns missing feature flags in return value
  .changeset/shiny-bushes-stare.md
  packages/browser/src/__tests__/featureflags.test.ts
  packages/browser/src/posthog-featureflags.ts
Labels: release

#2328 chore: add support for throttleDelayMs
  .changeset/two-shirts-itch.md
  examples/example-expo-53/package.json
  examples/example-expo-53/pnpm-lock.yaml
  packages/react-native/package.json
  packages/react-native/src/posthog-rn.ts
  packages/react-native/src/types.ts
  pnpm-lock.yaml
Labels: release

#2337 fix(nextjs-config): fix windows execution
  .changeset/thin-hoops-fix.md
  packages/nextjs-config/src/utils.ts
Labels: release

#2341 fix(err): infinite exception loop
  .changeset/every-dingos-live.md
  packages/browser/src/entrypoints/exception-autocapture.ts
  packages/browser/src/extensions/exception-autocapture/index.ts
  packages/browser/src/utils/globals.ts
Labels: release

#2344 fix: mark renderSurvey as deprecated
  .changeset/rude-memes-begin.md
  packages/browser/src/posthog-core.ts
Labels: feature/surveys, release

#2346 fix: node onException autocapture safely access the exception_List
  .changeset/cruel-bananas-slide.md
  packages/node/src/extensions/error-tracking/index.ts
Labels: release

#2347 feat: allow ignoring rageclick by css selector
  .changeset/loud-eels-tan.md
  packages/browser/src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  packages/browser/src/__tests__/autocapture.test.ts
  packages/browser/src/autocapture-utils.ts
  packages/browser/src/autocapture.ts
  packages/browser/src/types.ts
Labels: release

#2345 feat: surveys matching on event properties
  .changeset/yummy-experts-enjoy.md
  packages/browser/playwright/mocked/surveys/event-property-filtering.spec.ts
  packages/browser/src/__tests__/utils/survey-event-receiver.test.ts
  packages/browser/src/posthog-surveys-types.ts
  packages/browser/src/utils/survey-event-receiver.ts
Labels: release

#2354 fix: ensure consistent system prompts
  .changeset/great-horses-stare.md
  packages/ai/src/gemini/index.ts
  packages/ai/src/openai/azure.ts
  packages/ai/src/openai/index.ts
  packages/ai/src/utils.ts
  packages/ai/tests/azure-openai.test.ts
  packages/ai/tests/gemini.test.ts
  packages/ai/tests/openai.test.ts
  packages/ai/tests/system-prompts-utils.test.ts
Labels: release

#2356 chore(node): use core error tracking processing
  .changeset/eighty-seas-drive.md
  .changeset/wicked-cameras-brake.md
  examples/example-nextjs/pnpm-lock.yaml
  packages/core/src/error-tracking/error-properties-builder.ts
  packages/node/src/__tests__/extensions/error-conversion.spec.ts
  packages/node/src/__tests__/extensions/exception-autocapture.spec.ts
  packages/node/src/__tests__/extensions/exception-autocapture.worker.mjs
  packages/node/src/client.ts
  packages/node/src/entrypoints/index.edge.ts
  packages/node/src/entrypoints/index.node.ts
  packages/node/src/extensions/error-tracking/autocapture.ts
  packages/node/src/extensions/error-tracking/chunk-ids.ts
  packages/node/src/extensions/error-tracking/error-conversion.ts
  packages/node/src/extensions/error-tracking/index.ts
  packages/node/src/extensions/error-tracking/modifiers/context-lines.node.ts
  packages/node/src/extensions/error-tracking/modifiers/module.node.ts
  packages/node/src/extensions/error-tracking/reduceable-cache.ts
  packages/node/src/extensions/error-tracking/stack-parser.ts
  packages/node/src/extensions/error-tracking/type-checking.ts
  packages/node/src/extensions/error-tracking/types.ts
  packages/node/src/extensions/express.ts
  packages/node/src/extensions/sentry-integration.ts
Labels: release

#2362 fix: over eager rename of onRemoteConfig
  .changeset/chatty-planets-rescue.md
  packages/browser/src/extensions/replay/triggerMatching.ts
Labels: release

#2368 fix: recording should stop on forced idle and (conditionally) start on return
  .changeset/famous-books-slide.md
  packages/browser/playwright/mocked/session-recording/session-recording-idle-timeout.spec.ts
  packages/browser/src/__tests__/sessionid.test.ts
  packages/browser/src/extensions/replay/external/lazy-loaded-session-recorder.ts
  packages/browser/src/sessionid.ts
  packages/browser/terser-mangled-names.json
Labels: release

#2373 fix: 2 small conditional recording fixes
  .changeset/eager-taxes-spend.md
  packages/browser/playwright/mocked/session-recording/lazy-session-recording-sampling.spec.ts
  packages/browser/playwright/mocked/session-recording/lazy-session-recording.spec.ts
  packages/browser/src/__tests__/extensions/replay/lazy-sessionrecording.test.ts
  packages/browser/src/extensions/replay/external/lazy-loaded-session-recorder.ts
Labels: release

#2370 fix(core): remove testing export from posthog-core
  .changeset/early-carrots-bet.md
  .changeset/itchy-keys-remain.md
  packages/core/package.json
  packages/core/src/index.ts
  packages/node/src/__tests__/extensions/sentry-integration.spec.ts
  packages/node/src/__tests__/feature-flags.flags.spec.ts
  packages/node/src/__tests__/feature-flags.spec.ts
  packages/node/src/__tests__/posthog-node.spec.ts
  packages/node/src/__tests__/utils/index.ts
Labels: release

#2378 fix: don't mangle to dollar in any build
  .changeset/beige-corners-camp.md
  packages/browser/rollup.config.mjs
Labels: release

#2382 chore: add SDK Doctor test files to /examples
  examples/example-sdk_dr/README.md
  examples/example-sdk_dr/test-feature-flag-misconfiguration.html
  examples/example-sdk_dr/test-time-based-detection.html
Labels: SDK Support
