Repository PostHog/posthog-js, pull requests merged in 2025-05, with the labels that each got.

#1875 feat: allow ANY or ALL matches for triggers
  package.json
  playwright/session-recording/triggerMatch-type.spec.ts
  rollup.config.js
  src/__tests__/extensions/replay/sessionRecording-onRemoteConfig.test.ts
  src/__tests__/extensions/replay/sessionRecordingStatus.test.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/replay/triggerMatching.ts
  src/types.ts
  terser-mangled-names.json
Labels: bump minor

#1910 feat: Avoid tracking pageview from prerenders
  package.json
  pnpm-lock.yaml
  src/posthog-core.ts
  terser-mangled-names.json
Labels: bump minor

#1934 fix: dont mangle some surveys properties
  rollup.config.js
  terser-mangled-names.json
Labels: bump patch, feature/surveys

#1888 feat: submit partial responses for survey answers
  playground/nextjs/pages/_app.tsx
  playwright/surveys/question-types.spec.ts
  playwright/surveys/response-capture.spec.ts
  src/__tests__/extensions/surveys.test.ts
  src/__tests__/extensions/surveys/question-types.test.tsx
  src/__tests__/extensions/surveys/survey-popup.test.tsx
  src/__tests__/posthog-surveys.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/surveys-extension-utils.tsx
  src/posthog-surveys.ts
  src/utils/survey-utils.ts
Labels: bump minor, feature/surveys

#1939 fix: getRenderSurvey behavior
  src/__tests__/posthog-surveys.test.ts
  src/posthog-surveys.ts
Labels: bump patch, feature/surveys

#1944 fix: false flag should not trigger linked flags
  playwright/session-recording/session-recording-linked-flags.spec.ts
  playwright/utils/posthog-playwright-test-base.ts
  playwright/utils/setup.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/triggerMatching.ts
Labels: bump patch

#1942 chore: include response within the survey_quesiton property
  playwright/surveys/question-types.spec.ts
  playwright/surveys/response-capture.spec.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-extension-utils.tsx
Labels: bump patch, feature/surveys

#1945 chore: make rollup able to bundle CSS files
  jest.config.js
  package.json
  pnpm-lock.yaml
  rollup.config.js
Labels: feature/surveys

#1948 feat: use css files for survey widget styles
  src/__tests__/extensions/surveys/feedback-widget.test.tsx
  src/declaration.d.ts
  src/extensions/surveys-widget.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-extension-utils.tsx
  src/extensions/surveys/widget.css
Labels: bump patch, feature/surveys

#1951 feat: Add calculateEventProperties to public API
  rollup.config.js
  src/__tests__/posthog-core.test.ts
  src/__tests__/posthog-core.ts
  src/extensions/segment-integration.ts
  src/posthog-core.ts
  terser-mangled-names.json
Labels: bump minor

#1953 fix: Remove initial person info from event payload
  src/__tests__/posthog-persistence.test.ts
  src/constants.ts
Labels: bump patch

#1950 feat: use css files for survey styles
  playwright/surveys/customization.spec.ts
  playwright/surveys/feedback-widget.spec.ts
  src/__tests__/extensions/surveys.test.ts
  src/__tests__/extensions/surveys/feedback-widget.test.tsx
  src/__tests__/extensions/surveys/question-types.test.tsx
  src/extensions/surveys-widget.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/BottomSection.tsx
  src/extensions/surveys/components/ConfirmationMessage.tsx
  src/extensions/surveys/components/PostHogLogo.tsx
  src/extensions/surveys/components/QuestionHeader.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/survey.css
  src/extensions/surveys/surveys-extension-utils.tsx
  src/extensions/surveys/widget.css
Labels: bump minor, feature/surveys

#1955 fix: retrieve survey shadow should include posthog argument
  src/extensions/surveys.tsx
Labels: bump patch

#1959 fix: center positioning for surveys
  src/extensions/surveys.tsx
Labels: bump patch, feature/surveys

#1960 chore: remove unused function from survey extensions
  src/entrypoints/surveys.ts
  src/utils/globals.ts
Labels: feature/surveys

#1952 fix: add new relic to payload host denylist
  src/__tests__/extensions/replay/config.test.ts
  src/extensions/replay/config.ts
Labels: bump patch

#1937 feat: suppression matching
  src/__tests__/posthog-exceptions.test.ts
  src/__tests__/utils.test.ts
  src/constants.ts
  src/extensions/surveys/surveys-extension-utils.tsx
  src/posthog-core.ts
  src/posthog-exceptions.ts
  src/posthog-surveys-types.ts
  src/types.ts
  src/utils/person-property-utils.ts
  src/utils/property-utils.ts
  terser-mangled-names.json
Labels: bump minor, stale

#1958 feat: allow answer question when clicking on the choice
  playwright/surveys/question-types.spec.ts
  src/__tests__/extensions/surveys/question-types.test.tsx
  src/extensions/surveys/components/BottomSection.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/survey.css
  src/extensions/surveys/surveys-extension-utils.tsx
  src/posthog-surveys-types.ts
Labels: bump minor, feature/surveys

#1965 feat: add new options for survey positions
  playground/nextjs/pages/_app.tsx
  playwright/surveys/customization.spec.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/ConfirmationMessage.tsx
  src/extensions/surveys/survey.css
  src/extensions/surveys/surveys-extension-utils.tsx
  src/posthog-surveys-types.ts
Labels: bump minor, feature/surveys

#1969 chore: update some dependencies
  package.json
  pnpm-lock.yaml
Labels: bump patch

#1972 fix: linked flag any variant match
  playwright/session-recording/session-recording-linked-flags.spec.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/triggerMatching.ts
Labels: bump patch

#1974 fix: Block newer google bots
  src/utils/blocked-uas.ts
Labels: bump minor

#1982 chore: sync with main repo
  src/extensions/surveys/survey.css
  src/extensions/surveys/surveys-extension-utils.tsx
Labels: bump patch, feature/surveys

#1986 feat(flags): add `advanced_only_evaluate_survey_feature_flags` config to explicitly only evaluate survey flags on the frontend
  src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  src/__tests__/posthog-core.loaded.test.ts
  src/posthog-core.ts
  src/posthog-featureflags.ts
  src/types.ts
Labels: bump minor
