Repository PostHog/posthog-js, pull requests merged in 2025-01, with the labels that each got.

#1634 feat: Add pageview and prev pageview tracking
  src/__tests__/page-view.test.ts
  src/__tests__/posthog-core.ts
  src/page-view.ts
  src/posthog-core.ts
Labels: bump patch

#1632 feat: Deprecate `sanitize_properties`
  src/posthog-core.ts
  src/types.ts
Labels: bump minor, stale

#1641 feat: Add a onPreviewSubmit callback to preview surveys
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/components/BottomSection.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/surveys-utils.tsx
Labels: bump minor

#1643 feat: custom webfont selection on surveys
  src/extensions/surveys/surveys-utils.tsx
  src/posthog-surveys-types.ts
Labels: bump patch

#1648 feat: add irclid and _kx as campaign parameters
  src/__tests__/customizations/setAllPersonProfilePropertiesAsPersonPropertiesForFlags.test.ts
  src/__tests__/personProcessing.test.ts
  src/utils/event-utils.ts
Labels: bump minor

#1650 fix: survey previews should never have the submit button disabled
  playground/nextjs/src/Header.tsx
  src/extensions/surveys/components/BottomSection.tsx
Labels: bump patch

#1649 chore: deduplicate subsequent identify calls
  src/__tests__/posthog-core.identify.test.ts
  src/posthog-core.ts
  src/utils/identify-utils.ts
Labels: bump minor

#1592 chore: upgrade rrweb to alpha.18
  package.json
  patches/@rrweb__record@2.0.0-alpha.18.patch
  patches/@rrweb__rrweb-plugin-console-record@2.0.0-alpha.18.patch
  pnpm-lock.yaml
Labels: waiting

#1661 fix: expose getNextSurveyStep to use in posthog
  src/entrypoints/surveys-preview.es.ts
  src/posthog-surveys.ts
Labels: bump patch

#1658 fix(): prevent person processing if /decide fails to fetch remote config
  src/__tests__/personProcessing.test.ts
  src/__tests__/posthog-core.ts
  src/posthog-core.ts
  src/utils/type-utils.ts
Labels: bump patch

#1670 fix: patch for css parsing performance
  patches/@rrweb__record@2.0.0-alpha.18.patch
  pnpm-lock.yaml
Labels: bump patch

#1669 fix: sentry integration fields
  src/extensions/sentry-integration.ts
  src/posthog-core.ts
Labels: bump patch

#1671 fix: set last reset date as event super property
  src/__tests__/posthog-core.identify.test.ts
  src/__tests__/posthog-core.reset.test.ts
  src/posthog-core.ts
Labels: bump patch

#1663 chore: better logging for surveys loaders
  functional_tests/identify.test.ts
  src/__tests__/cookieless.test.ts
  src/__tests__/helpers/posthog-instance.ts
  src/__tests__/loader.test.ts
  src/__tests__/posthog-core.identify.test.ts
  src/__tests__/segment.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-utils.tsx
  src/posthog-core.ts
  src/posthog-surveys.ts
Labels: bump patch

#1677 fix: cache nested loops
  patches/@rrweb__record@2.0.0-alpha.18.patch
  pnpm-lock.yaml
Labels: bump patch

#1678 fix: missing href on link
  patches/@rrweb__record@2.0.0-alpha.18.patch
  pnpm-lock.yaml
Labels: bump patch

#1679 fix: silence noisy surveys logging
  src/posthog-surveys.ts
Labels: bump patch

#1682 fix: correctly cache split css
  patches/@rrweb__record@2.0.0-alpha.18.patch
  playwright/session-recording/session-recording-network-recorder.spec.ts
  pnpm-lock.yaml
Labels: bump patch

#1687 fix: angular detection can be less blunt
  patches/@rrweb__record@2.0.0-alpha.18.patch
  pnpm-lock.yaml
Labels: bump patch

#1686 fix: Implement `isDeepEqual` manually
  .eslintrc.js
  react/src/context/PostHogProvider.tsx
  react/src/context/__tests__/PostHogProvider.test.jsx
  react/src/utils/__tests__/object-utils.test.ts
  react/src/utils/object-utils.ts
Labels: bump patch

#1688 fix: Fix hitting call stack limit when deep comparing circular objects
  react/src/utils/__tests__/object-utils.test.ts
  react/src/utils/object-utils.ts
Labels: bump patch

#1684 feat: Annotate our `scroll` events as `passive`
  src/entrypoints/dead-clicks-autocapture.ts
  src/extensions/rageclick.ts
  src/scroll-manager.ts
Labels: bump patch

#1674 feat: Ignore more OpenAI bots
  src/utils/blocked-uas.ts
Labels: bump minor

#1690 fix: bad rrweb patch
  patches/@rrweb__record@2.0.0-alpha.18.patch
  pnpm-lock.yaml
Labels: bump patch

#1691 fix: rrweb patch fix take 2
  patches/@rrweb__record@2.0.0-alpha.18.patch
  pnpm-lock.yaml
Labels: bump patch

#1694 refactor: Remove/deprecate/rename old options
  src/posthog-core.ts
  src/types.ts
Labels: bump minor

#1659 revert: "chore: upgrade rrweb to alpha.18"
  package.json
  patches/@rrweb__record@2.0.0-alpha.17.patch
  patches/@rrweb__rrweb-plugin-console-record@2.0.0-alpha.17.patch
  pnpm-lock.yaml
Labels: bump patch

#1695 fix: survey URL targeting should re-evaluate after the URL changes
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys.tsx
  src/posthog-surveys.ts
Labels: bump patch

#1681 docs: Add documentation to all of our init options
  src/posthog-core.ts
  src/types.ts
Labels: bump patch

#1689 feat: Add new rule to guarantee events are tracked as passive
  .eslintrc.js
  eslint-rules/custom-eslint-rules.test.js
  eslint-rules/no-add-event-listener.js
  playground/ie11/index.html
  playground/nextjs/pages/replay-examples/canvas.tsx
  src/autocapture.ts
  src/entrypoints/dead-clicks-autocapture.ts
  src/entrypoints/external-scripts-loader.ts
  src/entrypoints/recorder.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/surveys.tsx
  src/extensions/toolbar.ts
  src/heatmaps.ts
  src/posthog-core.ts
  src/retry-queue.ts
  src/scroll-manager.ts
  src/sessionid.ts
  src/utils/index.ts
Labels: bump patch

#1700 feat: sampling that can be shared
  src/customizations/before-send.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/sampling.ts
Labels: bump minor

#1703 docs: Add missing types
  src/types.ts
Labels: bump patch

#1697 feat: deprecate `featureFlags.override` in favor of `featureFlags.overrideFeatureFlags`, a new function that supports overriding flags and flag payloads
  src/__tests__/featureflags.test.ts
  src/posthog-featureflags.ts
Labels: bump minor

#1698 chore: add device types check
  src/__tests__/request-utils.test.ts
  src/__tests__/surveys.test.ts
  src/extensions/surveys/action-matcher.ts
  src/posthog-surveys-types.ts
  src/posthog-surveys.ts
  src/utils/request-utils.ts
  src/utils/string-utils.ts
  src/web-experiments.ts
Labels: bump minor

#1706 fix: never send when not sampled
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1708 feat: allow configuring request queue interval
  src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  src/__tests__/request-queue.test.ts
  src/__tests__/request.test.ts
  src/posthog-core.ts
  src/request-queue.ts
  src/request.ts
  src/retry-queue.ts
  src/types.ts
Labels: bump minor

#1710 chore: some rrweb type changes
  src/extensions/replay/sessionrecording.ts
Labels: bump patch
