Repository PostHog/posthog-js, pull requests merged in 2025-03, with the labels that each got.

#1772 feat: better positioning for survey selectors
  playground/nextjs/pages/survey.tsx
  src/extensions/surveys-widget.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-utils.tsx
Labels: bump minor, feature/surveys

#1775 fix: add semrush audit bot
  src/utils/blocked-uas.ts
Labels: bump patch

#1780 feat(web-analytics): Add $session property with an object of props on session_id lifecycle
  src/__tests__/posthog-core.ts
  src/__tests__/session-props.test.ts
  src/posthog-core.ts
  src/session-props.ts
Labels: bump minor

#1734 feat: support loading masking remotely
  playground/cypress/index.html
  playwright/session-recording/session-recording-masking.spec.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/constants.ts
  src/extensions/replay/sessionrecording.ts
  src/types.ts
Labels: bump minor

#1778 feat: Make `getQueryParams` more resilient
  src/__tests__/request-utils.test.ts
  src/utils/request-utils.ts
Labels: bump patch

#1781 fix(flags): pass along $initial_ person properties in decide requests automatically
  functional_tests/feature-flags.test.ts
  playwright/decide.spec.ts
  src/__tests__/featureflags.test.ts
  src/posthog-featureflags.ts
Labels: bump minor

#1783 feat: posthog feature component should report variant too
  playground/nextjs/README.md
  playground/nextjs/package.json
  playground/nextjs/pages/index.tsx
  playground/nextjs/pnpm-lock.yaml
  playground/nuxtjs/nuxt.config.ts
  playground/nuxtjs/package.json
  playground/nuxtjs/pnpm-lock.yaml
  react/src/components/PostHogFeature.tsx
  react/src/components/__tests__/PostHogFeature.test.jsx
Labels: bump patch

#1791 feat: Block yet another semrush crawler/bot
  src/utils/blocked-uas.ts
Labels: bump patch

#1792 fix: Fix site app loading
  src/__tests__/site-apps.ts
  src/site-apps.ts
  src/types.ts
Labels: bump minor

#1786 fix(flags): do not reset $anon_distinct_id after first decide call if advanced_disable_feature_flags_on_first_load is true
  src/posthog-featureflags.ts
Labels: bump patch

#1793 chore(flags): support handling optional `requestId`s in `/decide` responses
  src/__tests__/featureflags.test.ts
  src/posthog-featureflags.ts
  src/types.ts
Labels: bump patch

#1794 feat: add chunk_id to stack frames
  src/extensions/exception-autocapture/chunk-ids.ts
  src/extensions/exception-autocapture/error-conversion.ts
  src/extensions/exception-autocapture/stack-trace.ts
Labels: bump minor

#1790 fix: stop setting platform on sentry event
  src/extensions/sentry-integration.ts
Labels: bump patch

#1795 fix: Reverse error message
  react/src/context/PostHogProvider.tsx
Labels: bump patch

#1764 chore: use quesiton ID instead of question index if it's available
  package.json
  playwright/surveys/core-display-logic.spec.ts
  playwright/surveys/customization.spec.ts
  playwright/surveys/feedback-widget.spec.ts
  playwright/surveys/question-types.spec.ts
  playwright/surveys/response-capture.spec.ts
  playwright/surveys/thank-you-message.spec.ts
  src/__tests__/extensions/surveys.test.ts
  src/__tests__/surveys.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-utils.tsx
  src/posthog-surveys-types.ts
Labels: bump patch, feature/surveys

#1803 fix: Stop logging error when client is uninitialized
  react/src/context/PostHogProvider.tsx
Labels: bump patch

#1806 fix: handle non Error objects being passed to captureException
  playground/error-tracking/react-ts-esbuild/package.json
  src/posthog-core.ts
Labels: bump patch

#1804 fix: simple loader race protection
  src/__tests__/utils/external-scripts-loader.test.ts
  src/entrypoints/external-scripts-loader.ts
Labels: bump patch

#1809 fix: prettier needed running
  .husky/pre-push
  package.json
  src/__tests__/utils/external-scripts-loader.test.ts
Labels: bump patch

#1820 chore: update web vitals
  package.json
  playwright/web-vitals.spec.ts
  pnpm-lock.yaml
Labels: bump patch

#1823 chore: force version in package.json
  package.json
Labels: bump patch

#1825 chore: allow push to main in GH actions
  .husky/pre-push
Labels: bump patch

#1768 feat: no recording blob urls
  .eslintrc.js
  eslint-rules/no-external-replay-imports.js
  eslint-rules/no-external-replay-imports.test.js
  src/__tests__/extensions/replay/external/network-plugin.test.ts
  src/entrypoints/posthog-recorder.ts
  src/entrypoints/recorder.ts
  src/extensions/replay/external/network-plugin.ts
Labels: bump minor

#1831 chore: update posthog rrweb
  package.json
  pnpm-lock.yaml
Labels: bump patch

#1832 fix: check surveys timeout in the survey manager level
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys.tsx
Labels: bump patch, feature/surveys

#1835 fix: do not allow non string `$current_url` to be provided
  src/__tests__/posthog-core.ts
  src/posthog-core.ts
Labels: bump patch

#1840 feat: Screen dimensions and UA as person property
  src/__tests__/customizations/setAllPersonProfilePropertiesAsPersonPropertiesForFlags.test.ts
  src/utils/event-utils.ts
Labels: bump patch

#1838 feat(flags): Enjoy the benefits of `/decide?v=4`. `$feature_flag_called` events contain more details such as flag version
  playwright/session-recording/session-recording-network-recorder.spec.ts
  src/__tests__/posthog-core.loaded.test.ts
  src/__tests__/posthog-core.ts
  src/__tests__/utils/request-router.test.ts
  src/entrypoints/array.full.es5.ts
  src/posthog-featureflags.ts
Labels: bump patch

#1842 fix(flags): Revert "feat(flags): Enjoy the benefits of `/decide?v=4`. `$feature_flag_called` events contain more details such as flag version"
  playwright/session-recording/session-recording-network-recorder.spec.ts
  src/__tests__/posthog-core.loaded.test.ts
  src/__tests__/posthog-core.ts
  src/__tests__/utils/request-router.test.ts
  src/entrypoints/array.full.es5.ts
  src/posthog-featureflags.ts
Labels: bump patch

#1843 fix(flags): Enjoy the benefits of `/decide?v=4`
  playwright/session-recording/session-recording-network-recorder.spec.ts
  src/__tests__/posthog-core.loaded.test.ts
  src/__tests__/posthog-core.ts
  src/__tests__/utils/request-router.test.ts
  src/entrypoints/array.full.es5.ts
  src/posthog-featureflags.ts
Labels: bump patch

#1847 fix: Switch from regex to trim
  src/utils/string-utils.ts
Labels: bump patch

#1834 chore: add onSurveysLoaded listener
  src/__tests__/posthog-surveys.test.ts
  src/posthog-core.ts
  src/posthog-surveys-types.ts
  src/posthog-surveys.ts
Labels: bump patch, feature/surveys

#1771 feat: capture console errors
  src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  src/__tests__/extensions/exception-autocapture/exception-observer.test.ts
  src/entrypoints/exception-autocapture.ts
  src/extensions/exception-autocapture/index.ts
  src/types.ts
  src/utils/globals.ts
Labels: bump minor

#1850 feat: always include stack trace parsing
  src/entrypoints/exception-autocapture.ts
  src/extensions/exception-autocapture/error-conversion.ts
  src/posthog-core.ts
  src/types.ts
  src/utils/globals.ts
Labels: bump minor

#1851 fix: only load surveys if there are surveys and its enabled
  functional_tests/mock-server.ts
  src/__tests__/posthog-surveys.test.ts
  src/posthog-surveys-types.ts
  src/posthog-surveys.ts
  src/types.ts
Labels: bump patch

#1853 fix: do not always wrap console.error
  src/__tests__/extensions/exception-autocapture/exception-observer.test.ts
  src/extensions/exception-autocapture/index.ts
Labels: bump patch

#1855 chore: remove misleading log line
  src/extensions/exception-autocapture/index.ts
Labels: bump patch

#1859 fix: resetting sampling to null should clear sampling for users
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch
