Repository PostHog/posthog-js, pull requests merged in 2025-06, with the labels that each got.

#2006 fix: stop feedback surveys to re-render every second
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-extension-utils.tsx
  terser-mangled-names.json
Labels: bump patch, feature/surveys

#1999 feat: improve surveys accessibility
  rollup.config.js
  src/__tests__/extensions/surveys/question-types.test.tsx
  src/extensions/surveys.tsx
  src/extensions/surveys/components/ConfirmationMessage.tsx
  src/extensions/surveys/components/QuestionHeader.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/icons.tsx
  src/extensions/surveys/survey.css
Labels: bump minor, feature/surveys

#2000 feat(flags): replace `/decide` with `/flags&config=true`
  functional_tests/feature-flags.test.ts
  functional_tests/mock-server.ts
  playground/session-recordings/server.js
  playwright/autocapture-config.spec.ts
  playwright/before_send.spec.ts
  playwright/capture.spec.ts
  playwright/error-tracking.spec.ts
  playwright/flags.spec.ts
  playwright/opting-out.spec.ts
  playwright/session-recording/opting-out.spec.ts
  playwright/session-recording/session-recording-array-full.spec.ts
  playwright/session-recording/session-recording-ingestion-controls.spec.ts
  playwright/session-recording/session-recording-linked-flags.spec.ts
  playwright/session-recording/session-recording-masking.spec.ts
  playwright/session-recording/session-recording-network-recorder.spec.ts
  playwright/session-recording/session-recording-sampling.spec.ts
  playwright/session-recording/session-recording.spec.ts
  playwright/session-recording/triggerMatch-type.spec.ts
  playwright/surveys/core-display-logic.spec.ts
  playwright/surveys/customization.spec.ts
  playwright/surveys/feedback-widget.spec.ts
  playwright/surveys/question-types.spec.ts
  playwright/surveys/response-capture.spec.ts
  playwright/surveys/thank-you-message.spec.ts
  playwright/ua.spec.ts
  playwright/utils/setup.ts
  playwright/web-vitals.spec.ts
  rollup.config.js
  src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  src/__tests__/autocapture.test.ts
  src/__tests__/extensions/exception-autocapture/exception-observer.test.ts
  src/__tests__/extensions/replay/sessionRecording-onRemoteConfig.test.ts
  src/__tests__/extensions/replay/sessionRecordingStatus.test.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/__tests__/extensions/surveys.test.ts
  src/__tests__/extensions/web-vitals.test.ts
  src/__tests__/featureflags.test.ts
  src/__tests__/heatmaps.test.ts
  src/__tests__/personProcessing.test.ts
  src/__tests__/posthog-core.loaded.test.ts
  src/__tests__/posthog-core.ts
  src/__tests__/posthog-exceptions.test.ts
  src/__tests__/posthog-surveys.test.ts
  src/__tests__/remote-config.test.ts
  src/__tests__/site-apps.test.ts
  src/__tests__/surveys.test.ts
  src/__tests__/utils/request-router.test.ts
  src/__tests__/very-large-performance-data.json
  src/autocapture.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/replay/triggerMatching.ts
  src/posthog-core.ts
  src/posthog-featureflags.ts
  src/posthog-surveys.ts
  src/remote-config.ts
  src/types.ts
  src/utils/index.ts
  src/utils/request-router.ts
  terser-mangled-names.json
Labels: bump minor

#2015 fix: Fix crash when config has circular references
  src/__tests__/posthog-core.ts
  src/posthog-core.ts
Labels: bump patch

#2017 chore: update readme instructions
  packages/browser/README.md
Labels: bump minor

#2018 fix: fix check-package-version step
  .github/workflows/cd.yml
Labels: bump patch

#2022 fix: don't call ff events for surveys
  packages/browser/src/__tests__/surveys.test.ts
  packages/browser/src/extensions/surveys.tsx
Labels: bump patch, feature/surveys

#2016 fix: style problems in multiple/single-choice questions
  packages/browser/src/extensions/surveys.tsx
  packages/browser/src/extensions/surveys/components/QuestionTypes.tsx
  packages/browser/src/extensions/surveys/survey.css
  packages/browser/src/extensions/surveys/surveys-extension-utils.tsx
Labels: bump patch, feature/surveys

#2026 feat: add distinct id tracing header
  packages/browser/src/entrypoints/tracing-headers.ts
  packages/browser/src/extensions/tracing-headers.ts
  packages/browser/src/utils/globals.ts
Labels: bump minor

#2031 chore: new survey config
  packages/browser/src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  packages/browser/src/__tests__/extensions/surveys.test.ts
  packages/browser/src/__tests__/helpers/posthog-instance.ts
  packages/browser/src/extensions/surveys.tsx
  packages/browser/src/extensions/surveys/components/QuestionTypes.tsx
  packages/browser/src/posthog-core.ts
  packages/browser/src/types.ts
Labels: bump patch, feature/surveys

#2065 fix: word break on open ended choices
  packages/browser/src/extensions/surveys/components/QuestionTypes.tsx
  packages/browser/src/extensions/surveys/survey.css
Labels: bump patch, feature/surveys

#2056 fix: init surveys manager if surveys is disabled in the project settings
  packages/browser/src/__tests__/extensions/surveys.test.ts
  packages/browser/src/__tests__/posthog-surveys.test.ts
  packages/browser/src/extensions/surveys.tsx
  packages/browser/src/posthog-surveys.ts
  packages/browser/src/utils/globals.ts
  packages/browser/terser-mangled-names.json
Labels: bump patch

#2039 feat: push replay and person data to intercom and crisp chat
  README.md
  packages/browser/playground/nextjs/pages/_app.tsx
  packages/browser/playground/nextjs/pages/external_chat.tsx
  packages/browser/playground/nextjs/src/Header.tsx
  packages/browser/playground/nextjs/src/posthog.ts
  packages/browser/src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  packages/browser/src/entrypoints/array.full.es5.ts
  packages/browser/src/entrypoints/crisp-chat-integration.ts
  packages/browser/src/entrypoints/intercom-integration.ts
  packages/browser/src/extensions/external-integration.ts
  packages/browser/src/posthog-core.ts
  packages/browser/src/types.ts
  packages/browser/src/utils/globals.ts
Labels: bump minor
