Repository PostHog/posthog-js, pull requests merged in 2025-02, with the labels that each got.

#1713 fix: checking status is too blunt for paused status
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1712 refactor: Simplify `Posthog.init()` signature
  src/posthog-core.ts
Labels: bump patch

#1716 fix(flags): store setOnce properties in locally persisted feature flag props
  src/__tests__/posthog-core.identify.test.ts
  src/posthog-core.ts
Labels: bump patch

#1718 chore: small readability refactor to getActiveMatchingSurveys
  src/posthog-surveys.ts
Labels: bump patch

#1719 fix(flags): set default state values in feature flag hooks
  react/src/hooks/__tests__/featureFlags.test.jsx
  react/src/hooks/useActiveFeatureFlags.ts
  react/src/hooks/useFeatureFlagEnabled.ts
  react/src/hooks/useFeatureFlagPayload.ts
  react/src/hooks/useFeatureFlagVariantKey.ts
  src/types.ts
Labels: bump patch

#1722 fix: check url match twice because of potential race condition
  src/extensions/surveys.tsx
Labels: bump patch

#1724 fix: capture when argument is not a string
  playwright/error-tracking.spec.ts
  src/__tests__/extensions/exception-autocapture/error-conversion.test.ts
  src/entrypoints/exception-autocapture.ts
  src/extensions/exception-autocapture/error-conversion.ts
  src/posthog-core.ts
  src/types.ts
  src/utils/globals.ts
  src/utils/type-utils.ts
Labels: bump patch

#1726 feat: override exception capture clientside
  src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  src/__tests__/extensions/exception-autocapture/exception-observer.test.ts
  src/extensions/exception-autocapture/index.ts
  src/types.ts
Labels: bump minor

#1728 fix(no-code experiments): refactor (6)
  src/__tests__/web-experiments.test.ts
  src/web-experiments.ts
Labels: bump patch

#1733 fix: Revert check url match twice because of potential race condition
  src/extensions/surveys.tsx
Labels: bump patch

#1731 fix: unexpected undefined should be expected
  src/extensions/replay/sessionrecording.ts
Labels: bump patch

#1736 fix: heatmaps unload listener
  src/__tests__/heatmaps.test.ts
  src/heatmaps.ts
Labels: bump patch

#1737 fix: skip device type check if no devices set
  src/posthog-surveys.ts
Labels: bump patch, feature/surveys

#1729 feat(flags): Add remote config feature flag method that bypasses cached values
  src/posthog-featureflags.ts
  src/types.ts
Labels: bump minor

#1738 chore(flags): Fix confusing statement in getRemoteConfigPayload jsdoc comment
  src/posthog-featureflags.ts
Labels: bump patch

#1740 chore: limit height of multiple choice question
  src/extensions/surveys.tsx
  src/extensions/surveys/components/QuestionTypes.tsx
  src/extensions/surveys/surveys-utils.tsx
Labels: bump patch, feature/surveys

#1739 feat(web-analytics): Handle set_once latest props in a cross-subdomain way
  src/__tests__/personProcessing.test.ts
  src/__tests__/posthog-core.ts
  src/__tests__/session-props.test.ts
  src/posthog-core.ts
  src/posthog-persistence.ts
  src/session-props.ts
  src/utils/event-utils.ts
Labels: bump minor

#1743 feat: add more debug signals
  src/__tests__/posthog-core.ts
  src/posthog-core.ts
Labels: bump patch

#1745 fix: last seen survey date logic
  src/__tests__/extensions/surveys-utils.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-utils.tsx
Labels: bump patch, feature/surveys

#1746 fix(devex): update frontend/package.json when pushing to main repo
  .github/workflows/cd.yml
Labels: bump patch

#1748 fix: Fix types for `onFeatureFlags` callback
  src/posthog-core.ts
  src/posthog-featureflags.ts
Labels: bump patch

#1751 feat: Block Chrome-Lighthouse UA (used by ahrefs)
  src/__tests__/utils.test.ts
  src/utils/blocked-uas.ts
Labels: bump patch

#1750 fix: Remove circular dependency
  src/__tests__/request-utils.test.ts
  src/extensions/surveys/action-matcher.ts
  src/posthog-surveys.ts
  src/utils/index.ts
  src/utils/regex-utils.ts
  src/utils/string-utils.ts
  src/web-experiments.ts
Labels: bump patch

#1752 feat: allow widget surveys to be repeated indefinitely
  src/__tests__/extensions/surveys-utils.test.ts
  src/extensions/surveys/surveys-utils.tsx
  src/posthog-surveys-types.ts
Labels: bump minor

#1749 chore: Make `@rrweb/types` a peer dependency
  package.json
  src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  src/__tests__/extensions/replay/mutation-rate-limiter.test.ts
  src/__tests__/extensions/replay/sessionrecording-utils.test.ts
  src/__tests__/extensions/replay/sessionrecording.test.ts
  src/extensions/replay/mutation-rate-limiter.ts
  src/extensions/replay/sessionrecording-utils.ts
  src/extensions/replay/sessionrecording.ts
  src/extensions/replay/types/rrweb.ts
  src/types.ts
Labels: bump minor

#1757 feat: Add new `prepare_external_dependency_stylesheet` config option
  src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  src/extensions/surveys.tsx
  src/extensions/utils/stylesheet-loader.ts
  src/types.ts
Labels: bump minor

#1747 fix: initializing surveys twice and calling survey shown/dismissed more than once per survey
  src/__tests__/__snapshots__/config-snapshot.test.ts.snap
  src/__tests__/posthog-surveys.test.ts
  src/__tests__/surveys.test.ts
  src/constants.ts
  src/posthog-core.ts
  src/posthog-surveys.ts
  src/types.ts
Labels: bump patch, feature/surveys

#1759 fix: improve survey bundle size v2
  src/__tests__/surveys.test.ts
  src/entrypoints/surveys-preview.es.ts
  src/extensions/surveys.tsx
  src/posthog-core.ts
  src/posthog-surveys.ts
Labels: bump patch, feature/surveys

#1761 fix: dont show survey on url change, only hide it
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys.tsx
Labels: bump patch, feature/surveys

#1763 chore: support inherit font family on surveys
  src/__tests__/extensions/surveys-utils.test.ts
  src/extensions/surveys/surveys-utils.tsx
Labels: bump patch, feature/surveys

#1765 fix: nonce missing style script
  src/extensions/surveys-widget.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-utils.tsx
  src/extensions/utils/stylesheet-loader.ts
Labels: bump patch

#1758 feat(feature-flags): support quota limiting for feature flags
  src/__tests__/posthog-core.loaded.test.ts
  src/posthog-featureflags.ts
Labels: bump minor

#1767 fix: dont require double click to show feedback surveys
  src/__tests__/extensions/surveys.test.ts
  src/extensions/surveys.tsx
  src/extensions/surveys/surveys-utils.tsx
Labels: bump patch, feature/surveys
